### ISSUE TITLE
🐞 - Prettier should not break line before punctuation

### ISSUE THREAD

**Issue by nsbarsukov** [taiga-family/configurations#602]
### Code Example URL

https://github.com/taiga-family/maskito/blob/main/projects/demo/src/pages/frameworks/react/react-doc.template.html

### Description

```html
<strong>
    Use
    <a
        href="https://react.dev/reference/react-dom/components/common#ref-callback"
        rel="noreferrer"
        target="_blank"
        tuiLink
    >
        ref callback
    </a>!
</strong>
```

Run
```shell
prettier projects/demo/src/pages/frameworks/react/react-doc.template.html --write
```

<p align="center">⬇️ </p>

```html
<strong>
    Use
    <a
        href="https://react.dev/reference/react-dom/components/common#ref-callback"
        rel="noreferrer"
        target="_blank"
        tuiLink
    >
        ref callback
    </a>
    !
</strong>
```
<img width="722" alt="extra-space" src="https://github.com/user-attachments/assets/772edad0-3fff-43e0-a1eb-56b66e74cd2e">

### Taiga UI version

"@taiga-ui/prettier-config": "0.202.0"

### Browser Used

Chrome

### OS Used

macOS

**Comment by splincode** [comment]
@nsbarsukov use

```html
<strong>
    Use
    <a
        href="https://react.dev/reference/react-dom/components/common#ref-callback"
        rel="noreferrer"
        target="_blank"
        tuiLink
    >
        ref callback!
    </a>
</strong>

**Comment by splincode** [comment]
you can ask a question here:
https://github.com/prettier/prettier/issues

**Comment by nsbarsukov** [comment]
* https://github.com/prettier/prettier/issues/16686

**Comment by waterplea** [comment]
Let's close this in favor of prettier issue. Currently prettier either does not care about whitespace (since Angular removes it) or cares about it everywhere. It's not about Taiga or our prettier config at this point.
